(()=>{
'use strict';
const $=id=>document.getElementById(id);
const labels={super_admin:'SUPER ADMIN',owner:'DONO',admin:'ADMINISTRADOR',editor:'EDITOR'};
const leadLabels={novo:'Novo',em_contato:'Em contato',avaliacao:'Avaliação',comprado:'Comprado',descartado:'Descartado'};
let sb=null,currentUser=null,panelRole=null,items=[],photoItems=[],removedPhotoUrls=[];
const configured=TSVehicles.configured();

function show(id,on=true){$(id)?.classList.toggle('hidden',!on)}
function esc(s){return TSVehicles.esc(s)}
function canManageUsers(){return ['super_admin','owner'].includes(panelRole)}
function canDelete(){return ['super_admin','owner','admin'].includes(panelRole)}
function canSeeManagement(){return ['super_admin','owner','admin'].includes(panelRole)}
function publicVehicleUrl(v){return TSVehicles.publicPath(v)}
function storagePath(url){const marker='/storage/v1/object/public/vehicle-photos/';const i=String(url||'').indexOf(marker);return i<0?null:decodeURIComponent(String(url).slice(i+marker.length).split('?')[0])}
function digits(s){return String(s||'').replace(/\D/g,'')}
function whatsappHref(phone,text=''){let d=digits(phone);if(d&&!d.startsWith('55'))d='55'+d;return `https://wa.me/${d}${text?`?text=${encodeURIComponent(text)}`:''}`}

async function init(){
 $('notice').textContent=configured?'Supabase conectado. Estoque, fotos e permissões estão protegidos pelo banco.':'Conexão com Supabase pendente.';
 setupTabs();setupSmartOptions();setupPhotoInput();
 $('logout').onclick=logout;$('deniedLogout').onclick=logout;$('loginBtn').onclick=login;
 $('mfaEnrollBtn').onclick=verifyMfaEnrollment;$('mfaChallengeBtn').onclick=verifyExistingMfa;
 $('save').onclick=saveVehicle;$('cancel').onclick=clearVehicleForm;$('createUser').onclick=createUser;
 if(!configured){show('loginBox');return}
 sb=TSVehicles.client();
 const {data}=await sb.auth.getUser();
 if(data?.user){currentUser=data.user;await enter()}else show('loginBox');
}

async function login(){const email=$('email').value.trim(),password=$('password').value;$('loginMsg').textContent='Entrando...';const {error}=await sb.auth.signInWithPassword({email,password});if(error){$('loginMsg').textContent=error.message;return}currentUser=(await sb.auth.getUser()).data.user;$('loginMsg').textContent='';await enter()}
async function logout(){if(sb)await sb.auth.signOut();location.reload()}
async function getRole(){const {data,error}=await sb.rpc('current_user_panel_role');return error?null:data}
async function enter(){panelRole=await getRole();if(!panelRole){show('loginBox',false);show('deniedBox');return}show('loginBox',false);show('deniedBox',false);if(panelRole==='super_admin'){const ok=await requireSuperAdminMfa();if(!ok)return}await openPanel()}
async function openPanel(){show('mfaBox',false);show('shell');show('logout');show('rolePill');$('rolePill').textContent=labels[panelRole]||panelRole;show('usersTabBtn',canManageUsers());show('logsTabBtn',canSeeManagement());configureUserRoles();await Promise.all([loadStock(),loadDashboard()])}

async function requireSuperAdminMfa(){
 show('mfaBox');
 const {data:factors,error:fErr}=await sb.auth.mfa.listFactors();if(fErr){$('mfaMsg').textContent=fErr.message;return false}
 const verified=(factors?.totp||[]).filter(f=>f.status==='verified');
 const {data:aal}=await sb.auth.mfa.getAuthenticatorAssuranceLevel();
 if(verified.length&&aal?.currentLevel==='aal2')return true;
 if(verified.length){$('mfaTitle').textContent='Confirme seu código de segurança';show('mfaEnroll',false);show('mfaChallenge');$('mfaChallengeBtn').dataset.factorId=verified[0].id;return false}
 $('mfaTitle').textContent='Proteja seu Super Admin com MFA';show('mfaChallenge',false);show('mfaEnroll');
 const {data,error}=await sb.auth.mfa.enroll({factorType:'totp',friendlyName:'TS Multimarcas Super Admin'});if(error){$('mfaMsg').textContent=error.message;return false}
 $('mfaQr').src=data.totp.qr_code;$('mfaSecret').textContent=data.totp.secret;$('mfaEnrollBtn').dataset.factorId=data.id;return false
}
async function verifyMfaEnrollment(){const factorId=$('mfaEnrollBtn').dataset.factorId,code=$('mfaEnrollCode').value.trim();if(!factorId||code.length<6)return;const {data:ch,error:cErr}=await sb.auth.mfa.challenge({factorId});if(cErr){$('mfaMsg').textContent=cErr.message;return}const {error}=await sb.auth.mfa.verify({factorId,challengeId:ch.id,code});if(error){$('mfaMsg').textContent=error.message;return}$('mfaMsg').textContent='MFA ativado com sucesso.';await openPanel()}
async function verifyExistingMfa(){const factorId=$('mfaChallengeBtn').dataset.factorId,code=$('mfaChallengeCode').value.trim();if(!factorId||code.length<6)return;const {data:ch,error:cErr}=await sb.auth.mfa.challenge({factorId});if(cErr){$('mfaMsg').textContent=cErr.message;return}const {error}=await sb.auth.mfa.verify({factorId,challengeId:ch.id,code});if(error){$('mfaMsg').textContent=error.message;return}$('mfaMsg').textContent='';await openPanel()}

function setupTabs(){document.querySelectorAll('.tab').forEach(b=>b.onclick=async()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('[data-tab-panel]').forEach(p=>p.classList.add('hidden'));show(b.dataset.tab+'Tab');if(b.dataset.tab==='users')await loadUsers();if(b.dataset.tab==='logs')await loadLogs();if(b.dataset.tab==='overview')await loadDashboard()})}
function configureUserRoles(){if(!canManageUsers())return;const opts=panelRole==='super_admin'?[['owner','Dono — gerencia loja e equipe'],['admin','Administrador — gerencia estoque completo'],['editor','Editor — adiciona e edita veículos']]:[['admin','Administrador — gerencia estoque completo'],['editor','Editor — adiciona e edita veículos']];$('uRole').innerHTML='<option value="" selected disabled>Selecione</option>'+opts.map(([v,t])=>`<option value="${v}">${t}</option>`).join('');$('userHelp').textContent=panelRole==='super_admin'?'Você pode criar Dono, Administrador ou Editor.':'O Dono pode criar Administradores e Editores.'}

function fillDatalist(id,values){const el=$(id);if(el)el.innerHTML=values.map(v=>`<option value="${esc(v)}"></option>`).join('')}
function setupSmartOptions(){const models={'Chevrolet':['Onix','Onix Plus','Tracker','Montana','S10','Spin','Cruze','Equinox','Trailblazer'],'Volkswagen':['Polo','Virtus','Nivus','T-Cross','Taos','Saveiro','Amarok','Jetta','Tiguan'],'Fiat':['Argo','Cronos','Pulse','Fastback','Strada','Toro','Mobi','Fiorino'],'Toyota':['Corolla','Corolla Cross','Yaris','Yaris Sedan','Hilux','SW4','RAV4','Camry'],'Honda':['City','City Hatch','Civic','HR-V','WR-V','CR-V','Fit'],'Hyundai':['HB20','HB20S','Creta','Tucson','Santa Fe','Azera'],'Jeep':['Renegade','Compass','Commander','Wrangler','Grand Cherokee'],'Nissan':['Kicks','Versa','Sentra','Frontier','March'],'Renault':['Kwid','Sandero','Logan','Duster','Oroch','Kardian'],'Ford':['Ka','EcoSport','Ranger','Territory','Maverick','Bronco','Mustang'],'BMW':['118i','320i','330e','X1','X2','X3','X4','X5'],'Mercedes-Benz':['A 200','C 200','C 300','GLA 200','GLC 300','GLE 400'],'Audi':['A3','A4','A5','Q3','Q5','Q7'],'Kia':['Cerato','Sportage','Sorento','Stonic','Carnival'],'Mitsubishi':['ASX','Eclipse Cross','Outlander','L200 Triton','Pajero Sport'],'Peugeot':['208','2008','3008','Partner'],'Citroën':['C3','C3 Aircross','C4 Cactus','Basalt'],'Volvo':['XC40','XC60','XC90','S60'],'Caoa Chery':['Tiggo 5X','Tiggo 7','Tiggo 8','Arrizo 6'],'BYD':['Dolphin','Dolphin Mini','Song Plus','Song Pro','Yuan Plus','Seal','King'],'GWM':['Haval H6','Haval H6 GT','Ora 03','Tank 300'],'Porsche':['Macan','Cayenne','911','718','Panamera','Taycan'],'Land Rover':['Range Rover Evoque','Discovery Sport','Defender','Range Rover Sport'],'Ram':['Rampage','1500','2500','3500']};fillDatalist('brandOptions',Object.keys(models).concat(['Suzuki','Subaru','Mini','Lexus','Jaguar','JAC','Chery']).sort());const update=()=>{const key=Object.keys(models).find(k=>k.toLowerCase()===$('brand').value.trim().toLowerCase());fillDatalist('modelOptions',key?models[key]:[...new Set(Object.values(models).flat())].sort())};$('brand').addEventListener('input',update);fillDatalist('versionOptions',['1.0','1.0 Flex','1.0 Turbo','1.3 Flex','1.3 Turbo','1.4 Turbo','1.5','1.5 Turbo','1.6 Flex','1.8 Flex','2.0 Flex','2.0 Turbo','2.0 Diesel','Híbrido','Elétrico']);const years=[];for(let y=new Date().getFullYear()+1;y>=1980;y--)years.push(String(y));fillDatalist('yearOptions',years);fillDatalist('transmissionOptions',['Automático','Manual','CVT','Automatizado','Automático de 6 marchas','Automático de 8 marchas','Automático de 9 marchas']);fillDatalist('fuelOptions',['Gasolina','Álcool / Etanol','Flex','Diesel','Elétrico','Híbrido','Híbrido plug-in','GNV','Gasolina + GNV','Flex + GNV','Diesel + Elétrico']);fillDatalist('colorOptions',['Preto','Branco','Prata','Cinza','Vermelho','Azul','Verde','Marrom','Bege','Dourado','Amarelo','Laranja'])}

async function loadStock(){items=await TSVehicles.list();renderStock()}
function renderStock(){$('count').textContent=`${items.length} veículo${items.length===1?'':'s'}`;$('vehicleList').innerHTML=items.map(v=>`<div class="item"><img loading="lazy" src="${esc(TSVehicles.mainImage(v))}" alt="${esc(v.name)}"><div><h3>${esc(v.name||v.title)}</h3><p>${esc(v.year)}${v.model_year?'/'+esc(v.model_year):''} • ${esc(v.km)}<br>${esc(TSVehicles.money(v.promo_price||v.price))} • <span class="status">${esc(v.status||'disponivel')}</span>${v.featured?' • Destaque':''}<br>${Array.isArray(v.images)?v.images.length:(v.image?1:0)} foto(s)</p></div><div class="actions"><a class="btn small green" target="_blank" rel="noopener" href="${esc(publicVehicleUrl(v))}">Ver no site</a><button class="btn small" data-edit="${v.id}">Editar</button>${canDelete()?`<button class="btn small danger" data-delete="${v.id}">Excluir</button>`:''}</div></div>`).join('')||'<p class="muted">Nenhum veículo cadastrado.</p>';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editVehicle(b.dataset.edit));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteVehicle(b.dataset.delete))}
function setupPhotoInput(){$('photos').onchange=async e=>{const files=[...e.target.files];e.target.value='';if(photoItems.length+files.length>15){alert('Cada veículo pode ter no máximo 15 fotos.');return}$('uploadStatus').textContent='Otimizando fotos...';for(const file of files){if(!['image/jpeg','image/png','image/webp'].includes(file.type)){continue}const optimized=await compressImage(file);photoItems.push({kind:'new',file:optimized,preview:URL.createObjectURL(optimized)})}renderPhotos();$('uploadStatus').textContent=`${photoItems.length}/15 fotos selecionadas.`}}
async function compressImage(file){try{const bmp=await createImageBitmap(file),max=1800,scale=Math.min(1,max/Math.max(bmp.width,bmp.height)),w=Math.round(bmp.width*scale),h=Math.round(bmp.height*scale),canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;canvas.getContext('2d').drawImage(bmp,0,0,w,h);bmp.close();const blob=await new Promise((res,rej)=>canvas.toBlob(b=>b?res(b):rej(new Error('Falha ao otimizar imagem')),'image/webp',.82));return new File([blob],file.name.replace(/\.[^.]+$/,'')+'.webp',{type:'image/webp'})}catch{return file}}
function renderPhotos(){$('photoGrid').innerHTML=photoItems.map((p,i)=>`<div class="photo ${i===0?'main':''}"><img src="${esc(p.kind==='existing'?p.url:p.preview)}"><div class="photo-controls"><button data-photo-action="left" data-i="${i}" title="Mover para esquerda">←</button><button data-photo-action="cover" data-i="${i}" title="Definir capa">Capa</button><button data-photo-action="right" data-i="${i}" title="Mover para direita">→</button><button data-photo-action="remove" data-i="${i}" title="Remover">×</button></div></div>`).join('');document.querySelectorAll('[data-photo-action]').forEach(b=>b.onclick=()=>photoAction(b.dataset.photoAction,Number(b.dataset.i)))}
function photoAction(action,i){if(action==='cover'&&i>0){photoItems.unshift(photoItems.splice(i,1)[0])}else if(action==='left'&&i>0){[photoItems[i-1],photoItems[i]]=[photoItems[i],photoItems[i-1]]}else if(action==='right'&&i<photoItems.length-1){[photoItems[i+1],photoItems[i]]=[photoItems[i],photoItems[i+1]]}else if(action==='remove'){const p=photoItems.splice(i,1)[0];if(p?.kind==='existing')removedPhotoUrls.push(p.url);if(p?.preview)URL.revokeObjectURL(p.preview)}renderPhotos()}
async function uploadPhotoItems(){const output=[],newUrls=[];let n=0;for(const p of photoItems){if(p.kind==='existing'){output.push(p.url);continue}n++;$('uploadStatus').textContent=`Enviando foto ${n}...`;const ext=p.file.type==='image/webp'?'webp':(p.file.name.split('.').pop()||'jpg').toLowerCase(),path=`${currentUser.id}/${Date.now()}-${crypto.randomUUID()}.${ext}`;const {error}=await sb.storage.from('vehicle-photos').upload(path,p.file,{cacheControl:'31536000',upsert:false});if(error)throw error;const url=sb.storage.from('vehicle-photos').getPublicUrl(path).data.publicUrl;output.push(url);newUrls.push(url)}return{output,newUrls}}
async function deleteStorageUrls(urls){const paths=urls.map(storagePath).filter(Boolean);if(paths.length)await sb.storage.from('vehicle-photos').remove(paths)}
function vehicleFormData(images){const brand=$('brand').value.trim(),model=$('model').value.trim(),version=$('version').value.trim(),name=[brand,model,version].filter(Boolean).join(' ');return{name,title:name,brand,model,version,year:$('year').value.trim(),model_year:$('modelYear').value.trim(),km:$('km').value.trim(),transmission:$('transmission').value.trim(),fuel:$('fuel').value.trim(),color:$('color').value.trim(),price:TSVehicles.money($('price').value),promo_price:TSVehicles.money($('promoPrice').value),description:$('description').value.trim(),images,image:images[0]||'',status:$('status').value,featured:$('featured').checked}}
async function saveVehicle(){if(!$('brand').value.trim()||!$('model').value.trim()||!$('price').value.trim()||!$('status').value){alert('Preencha marca, modelo, preço e status.');return}if(photoItems.length>15){alert('Máximo de 15 fotos.');return}const btn=$('save');let newUrls=[];try{btn.disabled=true;btn.textContent='SALVANDO...';const uploaded=await uploadPhotoItems();newUrls=uploaded.newUrls;const data=vehicleFormData(uploaded.output),id=$('vid').value;const r=id?await sb.from('vehicles').update(data).eq('id',id):await sb.from('vehicles').insert(data);if(r.error)throw r.error;await deleteStorageUrls(removedPhotoUrls);clearVehicleForm();await Promise.all([loadStock(),loadDashboard()])}catch(e){await deleteStorageUrls(newUrls);alert(e.message||'Não foi possível salvar o veículo.')}finally{btn.disabled=false;btn.textContent='SALVAR VEÍCULO';$('uploadStatus').textContent=''}}
function editVehicle(id){const v=items.find(x=>String(x.id)===String(id));if(!v)return;$('vid').value=v.id;$('brand').value=v.brand||'';$('model').value=v.model||'';$('version').value=v.version||'';$('year').value=v.year||'';$('modelYear').value=v.model_year||'';$('km').value=v.km||'';$('price').value=v.price||'';$('promoPrice').value=v.promo_price||'';$('transmission').value=v.transmission||'';$('fuel').value=v.fuel||'';$('color').value=v.color||'';$('description').value=v.description||'';$('status').value=v.status||'';$('featured').checked=!!v.featured;photoItems=(Array.isArray(v.images)&&v.images.length?v.images:(v.image?[v.image]:[])).map(url=>({kind:'existing',url}));removedPhotoUrls=[];renderPhotos();$('formTitle').textContent='Editar veículo';show('cancel');scrollTo({top:0,behavior:'smooth'})}
async function deleteVehicle(id){if(!canDelete()||!confirm('Excluir este veículo definitivamente?'))return;const v=items.find(x=>String(x.id)===String(id));const urls=(v?.images||[]).length?v.images:(v?.image?[v.image]:[]);const {error}=await sb.from('vehicles').delete().eq('id',id);if(error){alert(error.message);return}await deleteStorageUrls(urls);await Promise.all([loadStock(),loadDashboard()])}
function clearVehicleForm(){$('vid').value='';['brand','model','version','year','modelYear','km','price','promoPrice','transmission','fuel','color','description'].forEach(id=>$(id).value='');$('status').value='';$('featured').checked=false;photoItems.forEach(p=>p.preview&&URL.revokeObjectURL(p.preview));photoItems=[];removedPhotoUrls=[];renderPhotos();$('formTitle').textContent='Adicionar veículo';show('cancel',false)}

async function loadDashboard(){try{const {data:vs,error}=await sb.from('vehicles').select('id,name,slug,status,featured,created_at');if(error)throw error;const vehicles=vs||[];$('mAvailable').textContent=vehicles.filter(v=>v.status==='disponivel').length;$('mSold').textContent=vehicles.filter(v=>v.status==='vendido').length;$('mFeatured').textContent=vehicles.filter(v=>v.featured&&v.status==='disponivel').length;if(!canSeeManagement()){$('mLeads').textContent='—';$('mViews').textContent='—';$('mWhats').textContent='—';$('recentLeads').innerHTML='<p class="muted">Métricas comerciais disponíveis para Administrador, Dono e Super Admin.</p>';return}const since=new Date(Date.now()-30*864e5).toISOString();const [{data:leads},{data:events}]=await Promise.all([sb.from('leads').select('*').order('created_at',{ascending:false}).limit(20),sb.from('vehicle_events').select('vehicle_id,event_type,created_at').gte('created_at',since)]);$('mLeads').textContent=(leads||[]).filter(l=>l.status==='novo').length;$('mViews').textContent=(events||[]).filter(e=>e.event_type==='view').length;$('mWhats').textContent=(events||[]).filter(e=>e.event_type==='whatsapp').length;renderRecentLeads(leads||[]);renderTopVehicles(vehicles,events||[])}catch(e){console.error(e)}}
function renderRecentLeads(leads){$('recentLeads').innerHTML=leads.slice(0,8).map(l=>`<div class="lead-card"><div><h3>${esc(l.name)}</h3><p>${esc(l.brand)} ${esc(l.model)} ${esc(l.year)}<br>${esc(l.whatsapp)} · ${new Date(l.created_at).toLocaleString('pt-BR')}</p></div><div class="actions"><a class="btn small green" target="_blank" rel="noopener" href="${esc(whatsappHref(l.whatsapp,`Olá ${l.name}, recebemos sua solicitação de avaliação do ${l.brand} ${l.model}.`))}">WhatsApp</a><select class="field" style="width:auto;margin:0" data-lead-status="${l.id}">${Object.entries(leadLabels).map(([v,t])=>`<option value="${v}" ${l.status===v?'selected':''}>${t}</option>`).join('')}</select></div></div>`).join('')||'<p class="muted">Nenhum lead recebido ainda.</p>';document.querySelectorAll('[data-lead-status]').forEach(s=>s.onchange=()=>updateLeadStatus(s.dataset.leadStatus,s.value))}
async function updateLeadStatus(id,status){const {error}=await sb.from('leads').update({status}).eq('id',id);if(error){alert(error.message);return}await loadDashboard()}
function renderTopVehicles(vehicles,events){const map=new Map();events.forEach(e=>{const x=map.get(e.vehicle_id)||{view:0,whatsapp:0};x[e.event_type]=(x[e.event_type]||0)+1;map.set(e.vehicle_id,x)});const rows=vehicles.map(v=>({v,m:map.get(v.id)||{view:0,whatsapp:0}})).sort((a,b)=>(b.m.view+b.m.whatsapp*3)-(a.m.view+a.m.whatsapp*3)).slice(0,8);$('topVehicles').innerHTML=rows.map(({v,m})=>`<div class="log-card"><p><strong>${esc(v.name)}</strong><br>${m.view} visualizações · ${m.whatsapp} cliques no WhatsApp</p></div>`).join('')||'<p class="muted">As métricas aparecerão após as primeiras visitas.</p>'}

async function callUsers(body){const {data,error}=await sb.functions.invoke('manage-panel-users',{body});if(error)throw error;if(data?.error)throw new Error(data.error);return data}
function roleOptionsFor(u){const allowed=panelRole==='super_admin'?['owner','admin','editor']:['admin','editor'];return allowed.map(r=>`<option value="${r}" ${u.role===r?'selected':''}>${labels[r]}</option>`).join('')}
async function loadUsers(){if(!canManageUsers())return;try{const data=await callUsers({action:'list'}),users=data.users||[];$('userCount').textContent=`${users.length} usuários`;$('userList').innerHTML=users.map(u=>{const locked=u.role==='super_admin'||(panelRole==='owner'&&u.role==='owner')||currentUser?.id===u.id;return `<div class="user-card"><div><h3>${esc(u.display_name||u.email||'Usuário')}</h3><p>${esc(u.email)} · <span class="role">${labels[u.role]||u.role}</span>${u.last_sign_in_at?`<br>Último acesso: ${new Date(u.last_sign_in_at).toLocaleString('pt-BR')}`:''}</p></div><div class="actions"><select class="field" style="width:auto;margin:0" id="role-${u.id}" ${locked?'disabled':''}>${roleOptionsFor(u)}</select><button class="btn small" data-save-user="${u.id}" ${locked?'disabled':''}>Salvar</button><button class="btn small danger" data-delete-user="${u.id}" ${locked?'disabled':''}>Remover</button></div></div>`}).join('');document.querySelectorAll('[data-save-user]').forEach(b=>b.onclick=()=>saveUserRole(b.dataset.saveUser));document.querySelectorAll('[data-delete-user]').forEach(b=>b.onclick=()=>deleteUser(b.dataset.deleteUser))}catch(e){$('userList').innerHTML=`<p class="warn">${esc(e.message)}</p>`}}
async function createUser(){try{if(!$('uRole').value)throw new Error('Selecione o nível de acesso.');$('userMsg').textContent='Criando...';await callUsers({action:'create',display_name:$('uName').value.trim(),email:$('uEmail').value.trim(),password:$('uPassword').value,role:$('uRole').value});$('uName').value=$('uEmail').value=$('uPassword').value='';$('uRole').value='';$('userMsg').textContent='Usuário criado com sucesso.';await Promise.all([loadUsers(),loadLogs()])}catch(e){$('userMsg').textContent=e.message}}
async function saveUserRole(id){try{await callUsers({action:'update',id,role:$('role-'+id).value});await Promise.all([loadUsers(),loadLogs()])}catch(e){alert(e.message)}}
async function deleteUser(id){if(!confirm('Remover este acesso?'))return;try{await callUsers({action:'delete',id});await Promise.all([loadUsers(),loadLogs()])}catch(e){alert(e.message)}}

async function loadLogs(){if(!canSeeManagement())return;const {data,error}=await sb.from('activity_logs').select('*').order('created_at',{ascending:false}).limit(100);if(error){$('logList').innerHTML=`<p class="warn">${esc(error.message)}</p>`;return}$('logList').innerHTML=(data||[]).map(log=>`<div class="log-card"><p><strong>${esc(log.actor_name||labels[log.actor_role]||'Sistema')}</strong> — ${esc(actionText(log))}<br>${esc(log.entity_label||'')}</p><time>${new Date(log.created_at).toLocaleString('pt-BR')}</time></div>`).join('')||'<p class="muted">Nenhuma atividade registrada ainda.</p>'}
function actionText(l){const map={vehicle_created:'adicionou um veículo',vehicle_updated:'alterou um veículo',vehicle_deleted:'excluiu um veículo',user_created:'criou um usuário',user_updated:'alterou um usuário',user_deleted:'removeu um usuário',lead_created:'novo lead recebido',lead_status_changed:'alterou o status de um lead'};return map[l.action]||l.action}

window.addEventListener('DOMContentLoaded',init);
})();