-- TS Multimarcas — baseline seguro do banco
-- Este arquivo NÃO cria o primeiro Super Admin automaticamente.
-- O usuário inicial deve ser provisionado de forma controlada após o Auth.

create extension if not exists pgcrypto;
create schema if not exists private;

create table if not exists public.panel_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'editor' check (role in ('super_admin','owner','admin','editor')),
  display_name text,
  created_at timestamptz not null default now()
);
alter table public.panel_users enable row level security;

create or replace function private.current_panel_role()
returns text language sql stable security definer set search_path=''
as $$ select role from public.panel_users where user_id=(select auth.uid()) limit 1 $$;
create or replace function private.can_manage_stock()
returns boolean language sql stable security definer set search_path=''
as $$ select coalesce(private.current_panel_role() in ('super_admin','owner','admin','editor'),false) $$;
create or replace function private.can_delete_stock()
returns boolean language sql stable security definer set search_path=''
as $$ select coalesce(private.current_panel_role() in ('super_admin','owner','admin'),false) $$;
create or replace function public.current_user_panel_role()
returns text language sql stable set search_path=''
as $$ select private.current_panel_role() $$;

revoke all on schema private from public;
grant usage on schema private to anon,authenticated;
revoke all on function private.current_panel_role() from public,anon;
grant execute on function private.current_panel_role() to authenticated;
revoke all on function private.can_manage_stock() from public;
grant execute on function private.can_manage_stock() to anon,authenticated;
revoke all on function private.can_delete_stock() from public,anon;
grant execute on function private.can_delete_stock() to authenticated;
revoke all on function public.current_user_panel_role() from public,anon;
grant execute on function public.current_user_panel_role() to authenticated;

revoke all on public.panel_users from anon,authenticated;
grant select on public.panel_users to authenticated;
drop policy if exists "Panel user can read own role" on public.panel_users;
create policy "Panel user can read own role" on public.panel_users for select to authenticated
using (user_id=(select auth.uid()) or private.current_panel_role() in ('super_admin','owner'));

create table if not exists public.vehicles (
  id bigint generated by default as identity primary key,
  title text not null default '',
  brand text not null default '',
  model text not null default '',
  year text not null default '',
  km text not null default '',
  transmission text not null default '',
  price text not null default '',
  image text not null default '',
  status text not null default 'disponivel' check (status in ('disponivel','vendido','arquivado')),
  featured boolean not null default false,
  created_at timestamptz not null default now(),
  name text not null default '',
  version text not null default '',
  model_year text not null default '',
  fuel text not null default '',
  color text not null default '',
  description text not null default '',
  images text[] not null default '{}',
  promo_price text not null default '',
  slug text,
  constraint vehicles_max_10_images check (cardinality(images)<=10)
);
create unique index if not exists vehicles_slug_uidx on public.vehicles(slug) where slug is not null;
alter table public.vehicles enable row level security;

drop policy if exists "Public can view available vehicles" on public.vehicles;
create policy "Public can view available vehicles" on public.vehicles for select to anon,authenticated
using (status='disponivel' or private.can_manage_stock());
drop policy if exists "Team can insert vehicles" on public.vehicles;
create policy "Team can insert vehicles" on public.vehicles for insert to authenticated with check (private.can_manage_stock());
drop policy if exists "Team can update vehicles" on public.vehicles;
create policy "Team can update vehicles" on public.vehicles for update to authenticated using (private.can_manage_stock()) with check (private.can_manage_stock());
drop policy if exists "Managers can delete vehicles" on public.vehicles;
create policy "Managers can delete vehicles" on public.vehicles for delete to authenticated using (private.can_delete_stock());
grant select on public.vehicles to anon;
grant select,insert,update,delete on public.vehicles to authenticated;
grant usage,select on sequence public.vehicles_id_seq to authenticated;

create or replace function public.vehicle_slug_base(input text)
returns text language sql immutable set search_path=''
as $$ select trim(both '-' from regexp_replace(regexp_replace(lower(translate(coalesce(input,''),'áàãâäéèêëíìîïóòõôöúùûüçñÁÀÃÂÄÉÈÊËÍÌÎÏÓÒÕÔÖÚÙÛÜÇÑ','aaaaaeeeeiiiiooooouuuucnAAAAAEEEEIIIIOOOOOUUUUCN')),'[^a-z0-9]+','-','g'),'-+','-','g')) $$;
create or replace function private.set_vehicle_slug()
returns trigger language plpgsql security definer set search_path=''
as $$ begin if new.slug is null or btrim(new.slug)='' then new.slug:=coalesce(nullif(public.vehicle_slug_base(new.name),''),'veiculo')||'-'||new.id::text; end if; return new; end $$;
drop trigger if exists set_vehicle_slug on public.vehicles;
create trigger set_vehicle_slug before insert on public.vehicles for each row execute function private.set_vehicle_slug();

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  actor_role text,
  actor_name text,
  action text not null,
  entity_type text not null,
  entity_id text,
  entity_label text,
  details jsonb not null default '{}',
  created_at timestamptz not null default now()
);
alter table public.activity_logs enable row level security;
revoke all on public.activity_logs from anon,authenticated;
grant select on public.activity_logs to authenticated;
drop policy if exists "Managers can view activity logs" on public.activity_logs;
create policy "Managers can view activity logs" on public.activity_logs for select to authenticated
using (private.current_panel_role() in ('super_admin','owner','admin'));

create or replace function private.current_panel_display_name()
returns text language sql stable security definer set search_path=''
as $$ select coalesce((select display_name from public.panel_users where user_id=auth.uid()),(select email from auth.users where id=auth.uid()),'Sistema') $$;
revoke all on function private.current_panel_display_name() from public,anon,authenticated;

create or replace function private.log_vehicle_activity()
returns trigger language plpgsql security definer set search_path=''
as $$ declare uid uuid:=auth.uid(); role_name text:=private.current_panel_role(); actor_label text:=private.current_panel_display_name(); clean_old jsonb; clean_new jsonb; begin
if tg_op='INSERT' then insert into public.activity_logs(actor_user_id,actor_role,actor_name,action,entity_type,entity_id,entity_label,details) values(uid,role_name,actor_label,'vehicle_created','vehicle',new.id::text,new.name,jsonb_build_object('after',to_jsonb(new)-'images'-'image'-'description')); return new;
elsif tg_op='UPDATE' then clean_old:=to_jsonb(old)-'images'-'image'-'description'; clean_new:=to_jsonb(new)-'images'-'image'-'description'; if clean_old is distinct from clean_new or old.images is distinct from new.images then insert into public.activity_logs(actor_user_id,actor_role,actor_name,action,entity_type,entity_id,entity_label,details) values(uid,role_name,actor_label,'vehicle_updated','vehicle',new.id::text,new.name,jsonb_build_object('before',clean_old,'after',clean_new,'photos_before',cardinality(old.images),'photos_after',cardinality(new.images))); end if; return new;
elsif tg_op='DELETE' then insert into public.activity_logs(actor_user_id,actor_role,actor_name,action,entity_type,entity_id,entity_label,details) values(uid,role_name,actor_label,'vehicle_deleted','vehicle',old.id::text,old.name,jsonb_build_object('before',to_jsonb(old)-'images'-'image'-'description')); return old; end if; return null; end $$;
drop trigger if exists log_vehicle_activity on public.vehicles;
create trigger log_vehicle_activity after insert or update or delete on public.vehicles for each row execute function private.log_vehicle_activity();

create table if not exists public.leads (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  whatsapp text not null,
  brand text not null,
  model text not null,
  year text not null default '',
  km text not null default '',
  notes text not null default '',
  status text not null default 'novo' check (status in ('novo','em_contato','avaliacao','comprado','descartado')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.leads enable row level security;
grant insert on public.leads to anon,authenticated;
grant select,update on public.leads to authenticated;
drop policy if exists "Public can submit leads" on public.leads;
create policy "Public can submit leads" on public.leads for insert to anon,authenticated with check (length(btrim(name)) between 2 and 100 and length(regexp_replace(whatsapp,'[^0-9]','','g')) between 10 and 13 and length(btrim(brand)) between 1 and 80 and length(btrim(model)) between 1 and 120);
drop policy if exists "Managers can view leads" on public.leads;
create policy "Managers can view leads" on public.leads for select to authenticated using (private.current_panel_role() in ('super_admin','owner','admin'));
drop policy if exists "Managers can update leads" on public.leads;
create policy "Managers can update leads" on public.leads for update to authenticated using (private.current_panel_role() in ('super_admin','owner','admin')) with check (private.current_panel_role() in ('super_admin','owner','admin'));
create or replace function private.touch_lead_updated_at() returns trigger language plpgsql set search_path='' as $$ begin new.updated_at:=now(); return new; end $$;
drop trigger if exists touch_lead_updated_at on public.leads;
create trigger touch_lead_updated_at before update on public.leads for each row execute function private.touch_lead_updated_at();
create or replace function private.log_lead_activity() returns trigger language plpgsql security definer set search_path='' as $$ begin if tg_op='INSERT' then insert into public.activity_logs(actor_user_id,actor_role,actor_name,action,entity_type,entity_id,entity_label,details) values(auth.uid(),private.current_panel_role(),case when auth.uid() is null then 'Visitante' else private.current_panel_display_name() end,'lead_created','lead',new.id::text,new.name,jsonb_build_object('brand',new.brand,'model',new.model,'status',new.status)); elsif tg_op='UPDATE' and old.status is distinct from new.status then insert into public.activity_logs(actor_user_id,actor_role,actor_name,action,entity_type,entity_id,entity_label,details) values(auth.uid(),private.current_panel_role(),private.current_panel_display_name(),'lead_status_changed','lead',new.id::text,new.name,jsonb_build_object('from',old.status,'to',new.status)); end if; return new; end $$;
drop trigger if exists log_lead_activity on public.leads;
create trigger log_lead_activity after insert or update on public.leads for each row execute function private.log_lead_activity();

create table if not exists public.vehicle_events (
  id bigint generated by default as identity primary key,
  vehicle_id bigint not null references public.vehicles(id) on delete cascade,
  event_type text not null check (event_type in ('view','whatsapp')),
  created_at timestamptz not null default now()
);
alter table public.vehicle_events enable row level security;
revoke all on public.vehicle_events from anon,authenticated;
grant select on public.vehicle_events to authenticated;
drop policy if exists "Managers can view vehicle events" on public.vehicle_events;
create policy "Managers can view vehicle events" on public.vehicle_events for select to authenticated using (private.current_panel_role() in ('super_admin','owner','admin'));
create or replace function public.track_vehicle_event(p_vehicle_id bigint,p_event_type text) returns void language plpgsql security definer set search_path='' as $$ begin if p_event_type not in ('view','whatsapp') then raise exception 'invalid event type'; end if; if not exists(select 1 from public.vehicles where id=p_vehicle_id and status='disponivel') then return; end if; insert into public.vehicle_events(vehicle_id,event_type) values(p_vehicle_id,p_event_type); end $$;
revoke all on function public.track_vehicle_event(bigint,text) from public;
grant execute on function public.track_vehicle_event(bigint,text) to anon,authenticated;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('vehicle-photos','vehicle-photos',true,10485760,array['image/jpeg','image/png','image/webp'])
on conflict(id) do update set public=true,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists "Public vehicle photos read" on storage.objects;
create policy "Public vehicle photos read" on storage.objects for select to public using (bucket_id='vehicle-photos');
drop policy if exists "Panel users upload vehicle photos" on storage.objects;
create policy "Panel users upload vehicle photos" on storage.objects for insert to authenticated with check (bucket_id='vehicle-photos' and private.current_panel_role() in ('super_admin','owner','admin','editor'));
drop policy if exists "Panel users update vehicle photos" on storage.objects;
create policy "Panel users update vehicle photos" on storage.objects for update to authenticated using (bucket_id='vehicle-photos' and private.current_panel_role() in ('super_admin','owner','admin','editor')) with check (bucket_id='vehicle-photos' and private.current_panel_role() in ('super_admin','owner','admin','editor'));
drop policy if exists "Managers delete vehicle photos" on storage.objects;
create policy "Managers delete vehicle photos" on storage.objects for delete to authenticated using (bucket_id='vehicle-photos' and private.current_panel_role() in ('super_admin','owner','admin'));

-- O gerenciamento de usuários usa a Edge Function manage-panel-users com JWT obrigatório.
-- Não adicione service_role ou outras chaves secretas neste arquivo ou no frontend.
