(function(){
  const demo=[
    {id:'demo-1',slug:'toyota-corolla-xei-2-0-flex-demo-1',name:'Toyota Corolla XEi 2.0 Flex',brand:'Toyota',model:'Corolla',version:'XEi 2.0 Flex',year:'2022',model_year:'2023',km:'28.000 km',transmission:'Automático',fuel:'Flex',price:'R$ 119.900',promo_price:'',image:'https://images.unsplash.com/photo-1623869675781-80aa31012a5a?auto=format&fit=crop&w=900&q=80',images:['https://images.unsplash.com/photo-1623869675781-80aa31012a5a?auto=format&fit=crop&w=900&q=80'],featured:true,status:'disponivel'},
    {id:'demo-2',slug:'jeep-compass-longitude-demo-2',name:'Jeep Compass Longitude 2.0 Flex',brand:'Jeep',model:'Compass',version:'Longitude 2.0 Flex',year:'2021',model_year:'2022',km:'45.000 km',transmission:'Automático',fuel:'Flex',price:'R$ 109.900',promo_price:'R$ 104.900',image:'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=900&q=80',images:['https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=900&q=80'],featured:true,status:'disponivel'}
  ];
  function configured(){return !!(window.TS_SUPABASE&&window.TS_SUPABASE.url&&window.TS_SUPABASE.anonKey&&window.supabase)}
  function client(){return configured()?window.supabase.createClient(window.TS_SUPABASE.url,window.TS_SUPABASE.anonKey):null}
  function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
  function money(value){const raw=String(value??'').trim();if(!raw)return'';const cleaned=raw.replace(/^R\$\s*/i,'').trim();return cleaned?`R$ ${cleaned}`:''}
  function mainImage(v){return(Array.isArray(v.images)&&v.images[0])||v.image||'logo-ts.svg'}
  function publicPath(v){return v.slug?`/veiculo/${encodeURIComponent(v.slug)}`:`/veiculo.html?id=${encodeURIComponent(v.id)}`}
  async function list(){if(!configured()){const local=JSON.parse(localStorage.getItem('ts_admin_demo_vehicles')||'null');return Array.isArray(local)&&local.length?local:demo}const {data,error}=await client().from('vehicles').select('*').order('created_at',{ascending:false});if(error)throw error;return(data||[]).map(v=>({...v,image:mainImage(v)}))}
  function priceHtml(v){const normal=money(v.price),promo=money(v.promo_price);return promo?`<div class="price-old">${esc(normal)}</div><div class="price">${esc(promo)}</div><span class="offer">OFERTA</span>`:`<div class="price">${esc(normal)}</div>`}
  function card(v){const sold=v.status==='vendido';const year=v.model_year&&v.year!==v.model_year?`${v.year||''}/${v.model_year}`:(v.year||v.model_year||'');const details=[year,v.km,v.transmission].filter(Boolean).join(' • ');return `<article class="car"><img loading="lazy" decoding="async" src="${esc(mainImage(v))}" alt="${esc(v.name||'Veículo')}"><div class="car-body"><h3>${esc(v.name||'')}</h3><div class="meta">${esc(details)}</div>${priceHtml(v)}${sold?'<span class="btn" style="opacity:.65;pointer-events:none">VENDIDO</span>':`<a class="btn" href="${esc(publicPath(v))}">VER VEÍCULO</a>`}</div></article>`}
  async function render(selector,options={}){const el=document.querySelector(selector);if(!el)return;try{let rows=await list();rows=rows.filter(v=>v.status!=='arquivado');if(options.featured)rows=rows.filter(v=>v.featured).slice(0,options.limit||6);el.innerHTML=rows.map(card).join('')||'<p style="color:#aaa">Nenhum veículo disponível.</p>'}catch(e){el.innerHTML='<p style="color:#aaa">Não foi possível carregar o estoque agora.</p>';console.error(e)}}
  async function track(vehicleId,eventType){if(!configured()||!vehicleId)return;try{await client().rpc('track_vehicle_event',{p_vehicle_id:Number(vehicleId),p_event_type:eventType})}catch(e){console.debug('metric',e)}}
  window.TSVehicles={demo,configured,client,esc,money,mainImage,publicPath,list,priceHtml,card,render,track};
})();